'use client';

import { useEffect, useState } from 'react';
import { Archive, Clock3, Save } from 'lucide-react';
import type { Lead, LeadHistory, LeadStatus } from '@/types/crm';
import type { LeadDraft } from '@/components/leads/new-lead-dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';

const stages: LeadStatus[] = ['Novo','Contato','Negociação','Fechado','Perdido'];
type FormState = Pick<LeadDraft,'name'|'company'|'email'|'phone'|'value'|'status'|'source'|'notes'|'nextActionAt'>;

export function LeadDetailSheet({leadId,onOpenChange,onUpdate,onArchive}:{leadId:string|null;onOpenChange:(open:boolean)=>void;onUpdate:(id:string,draft:Partial<LeadDraft>)=>Promise<Lead>;onArchive:(id:string)=>Promise<void>}){
  const [lead,setLead]=useState<Lead|null>(null); const [history,setHistory]=useState<LeadHistory[]>([]); const [form,setForm]=useState<FormState|null>(null); const [loading,setLoading]=useState(false); const [pending,setPending]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{if(!leadId)return;queueMicrotask(()=>{setLoading(true);setError('')});fetch(`/api/leads/${leadId}`).then(async(response)=>{const data=await response.json() as {lead?:Lead;history?:LeadHistory[];error?:string};if(!response.ok||!data.lead)throw new Error(data.error||'Não foi possível carregar o lead.');setLead(data.lead);setHistory(data.history||[]);setForm({name:data.lead.name,company:data.lead.company,email:data.lead.email,phone:data.lead.phone,value:String(data.lead.value),status:data.lead.status,source:data.lead.source||'',notes:data.lead.notes||'',nextActionAt:data.lead.nextActionAt?.slice(0,16)||''})}).catch((reason)=>setError(reason instanceof Error?reason.message:'Não foi possível carregar o lead.')).finally(()=>setLoading(false))},[leadId]);
  const set=(key:keyof FormState,value:string)=>setForm((current)=>current?{...current,[key]:value}:current);
  const save=async()=>{if(!leadId||!form)return;setPending(true);setError('');try{const updated=await onUpdate(leadId,form);setLead(updated);const response=await fetch(`/api/leads/${leadId}`);const data=await response.json() as {history?:LeadHistory[]};setHistory(data.history||history)}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível salvar.')}finally{setPending(false)}};
  const archive=async()=>{if(!leadId)return;setPending(true);setError('');try{await onArchive(leadId)}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível arquivar.');setPending(false)}};
  return <Sheet open={Boolean(leadId)} onOpenChange={onOpenChange}><SheetContent side="right" className="w-full overflow-y-auto border-[var(--line)] bg-[var(--surface-raised)] sm:max-w-xl"><SheetHeader className="border-b border-[var(--line-soft)] px-6 py-5"><SheetTitle className="text-xl text-[var(--text-strong)]">{lead?.name||'Detalhes do lead'}</SheetTitle><SheetDescription>{lead?.company||'Carregando informações...'}</SheetDescription></SheetHeader>
    {loading?<div className="p-8 text-sm text-[var(--text-soft)]">Carregando detalhes...</div>:form?<div className="space-y-7 p-6"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome"><Input value={form.name} onChange={(e)=>set('name',e.target.value)} className="premium-input"/></Field><Field label="Empresa"><Input value={form.company} onChange={(e)=>set('company',e.target.value)} className="premium-input"/></Field><Field label="Email"><Input type="email" value={form.email} onChange={(e)=>set('email',e.target.value)} className="premium-input"/></Field><Field label="Telefone"><Input value={form.phone} onChange={(e)=>set('phone',e.target.value)} className="premium-input"/></Field><Field label="Valor estimado"><Input type="number" min="0" value={form.value} onChange={(e)=>set('value',e.target.value)} className="premium-input"/></Field><Field label="Etapa"><select value={form.status} onChange={(e)=>set('status',e.target.value)} className="premium-input h-9 w-full rounded-md border px-3 text-sm outline-none">{stages.map((stage)=><option key={stage}>{stage}</option>)}</select></Field><Field label="Origem"><Input value={form.source} onChange={(e)=>set('source',e.target.value)} className="premium-input"/></Field><Field label="Próxima ação"><Input type="datetime-local" value={form.nextActionAt} onChange={(e)=>set('nextActionAt',e.target.value)} className="premium-input"/></Field><div className="sm:col-span-2"><Field label="Observações"><Textarea value={form.notes} onChange={(e)=>set('notes',e.target.value)} className="premium-input min-h-24"/></Field></div></div>
      {error&&<p role="alert" className="text-sm text-red-600 dark:text-red-300">{error}</p>}
      <div className="flex flex-wrap justify-between gap-3 border-t border-[var(--line-soft)] pt-5"><AlertDialog><AlertDialogTrigger render={<Button variant="outline" className="border-red-300 text-red-700 hover:bg-red-50 dark:text-red-300" disabled={pending}/> }><Archive size={15}/>Arquivar</AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Arquivar este lead?</AlertDialogTitle><AlertDialogDescription>Ele deixará de aparecer no pipeline, mas o histórico será preservado.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={archive} disabled={pending} className="bg-red-600 text-white hover:bg-red-700">Arquivar lead</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><Button onClick={save} disabled={pending||!form.name.trim()||!form.company.trim()} className="bg-[var(--brand-deep)] text-white dark:text-[#13231f]"><Save size={15}/>{pending?'Salvando...':'Salvar alterações'}</Button></div>
      <section><h3 className="font-semibold text-[var(--text-strong)]">Histórico</h3><div className="mt-4 space-y-0 border-l border-[var(--line)] pl-5">{history.map((item)=><article key={item.id} className="relative pb-5 before:absolute before:-left-[25px] before:top-1.5 before:size-2 before:rounded-full before:bg-[var(--success)]"><p className="text-sm font-medium text-[var(--text-strong)]">{item.description}</p><p className="mt-1 flex items-center gap-1.5 text-xs text-[var(--text-faint)]"><Clock3 size={12}/>{new Date(item.createdAt).toLocaleString('pt-BR')} · {item.authorName}</p></article>)}</div></section>
    </div>:<div className="p-8 text-sm text-red-600">{error||'Lead não encontrado.'}</div>}
  </SheetContent></Sheet>;
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block space-y-2"><span className="block text-xs font-medium text-[var(--text-soft)]">{label}</span>{children}</label>}
