'use client';
import { useEffect, useState } from 'react';
import type { Lead, LeadStatus } from '@/types/crm';
import { users } from '@/data/leads';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';

export type LeadDraft={name:string;company:string;email:string;phone:string;value:string;status:LeadStatus;ownerId:string;notes:string};
const empty:LeadDraft={name:'',company:'',email:'',phone:'',value:'',status:'Novo',ownerId:'João Martins',notes:''};

export function NewLeadDialog({open,onOpenChange,onCreate,initialDraft}:{open:boolean;onOpenChange:(v:boolean)=>void;onCreate:(lead:Lead)=>void;initialDraft?:Partial<LeadDraft>}){const [form,setForm]=useState(empty);useEffect(()=>{if(open)setForm({...empty,...initialDraft});else setForm(empty)},[open,initialDraft]);const set=(key:keyof LeadDraft,value:string)=>setForm(p=>({...p,[key]:value}));const submit=(e:React.FormEvent)=>{e.preventDefault();if(!form.name.trim()||!form.company.trim())return;onCreate({id:`l-${Date.now()}`,name:form.name,company:form.company,email:form.email,phone:form.phone,value:Number(form.value)||0,lastContact:'Agora',owner:users.find(u=>u.name===form.ownerId)??users[0],status:form.status,tags:['Novo'],notes:form.notes});onOpenChange(false)};return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] overflow-y-auto rounded-2xl sm:max-w-[620px]"><form onSubmit={submit}><DialogHeader><DialogTitle className="text-xl">Adicionar novo lead</DialogTitle><DialogDescription>Registre uma nova oportunidade no pipeline comercial.</DialogDescription></DialogHeader><div className="grid gap-4 py-5 sm:grid-cols-2"><Field label="Nome *"><Input required value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Nome completo"/></Field><Field label="Empresa *"><Input required value={form.company} onChange={e=>set('company',e.target.value)} placeholder="Nome da empresa"/></Field><Field label="Email"><Input type="email" value={form.email} onChange={e=>set('email',e.target.value)} placeholder="nome@empresa.com"/></Field><Field label="Telefone"><Input value={form.phone} onChange={e=>set('phone',e.target.value)} placeholder="(00) 00000-0000"/></Field><Field label="Valor estimado"><Input type="number" min="0" value={form.value} onChange={e=>set('value',e.target.value)} placeholder="R$ 0"/></Field><Field label="Status"><Select value={form.status} onValueChange={v=>set('status',v as LeadStatus)}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{['Novo','Contato','Negociação','Fechado','Perdido'].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></Field><Field label="Responsável"><Select value={form.ownerId} onValueChange={v=>set('ownerId',v)}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{users.map(u=><SelectItem key={u.id} value={u.name}>{u.name}</SelectItem>)}</SelectContent></Select></Field><div className="sm:col-span-2"><Field label="Observações"><Textarea value={form.notes} onChange={e=>set('notes',e.target.value)} placeholder="Contexto, necessidades e próximos passos..." className="min-h-24"/></Field></div></div><DialogFooter><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button className="bg-[#173f3d] hover:bg-[#0f302f]">Adicionar lead</Button></DialogFooter></form></DialogContent></Dialog>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
