'use client';
import { useCallback, useState } from 'react';
import { Bell, ChartNoAxesCombined, CircleUserRound, LayoutDashboard, Menu, Plus, Search, Settings, Sparkles, UsersRound } from 'lucide-react';
import type { Lead, LeadStatus } from '@/types/crm';
import { initialLeads } from '@/data/leads';
import { DashboardPage } from '@/components/dashboard/dashboard-page';
import { LeadsPage } from '@/components/leads/leads-page';
import { ClientsPage } from '@/components/clients/clients-page';
import { ActivitiesPage } from '@/components/activities/activities-page';
import { NewLeadDialog, type LeadDraft } from '@/components/leads/new-lead-dialog';
import { useWebMcpCreateLead } from '@/hooks/use-webmcp';
import { Button } from '@/components/ui/button';
import { Sheet, SheetContent, SheetTitle, SheetTrigger } from '@/components/ui/sheet';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';

type Page='Dashboard'|'Leads'|'Clientes'|'Atividades';
const nav=[{name:'Dashboard' as Page,icon:LayoutDashboard},{name:'Leads' as Page,icon:ChartNoAxesCombined},{name:'Clientes' as Page,icon:UsersRound},{name:'Atividades' as Page,icon:CircleUserRound}];

export function CRMApp(){const[page,setPage]=useState<Page>('Dashboard');const[leads,setLeads]=useState(initialLeads);const[modal,setModal]=useState(false);const[prefill,setPrefill]=useState<Partial<LeadDraft>>({});const startLead=useCallback((input:{name:string;company:string})=>{setPrefill(input);setModal(true)},[]);useWebMcpCreateLead(startLead);const move=(id:string,status:LeadStatus)=>setLeads(current=>current.map(l=>l.id===id?{...l,status,lastContact:'Agora'}:l));const create=(lead:Lead)=>{setLeads(current=>[lead,...current]);setPage('Leads')};const openNew=()=>{setPrefill({});setModal(true)};return <main className="min-h-screen bg-[#f5f7f7] text-[#172525] lg:grid lg:grid-cols-[232px_1fr]"><DesktopSidebar page={page} onNavigate={setPage}/><section className="min-w-0"><AppHeader page={page} onNavigate={setPage} onNew={openNew}/><div className="mx-auto max-w-[1500px] p-5 lg:p-8">{page==='Dashboard'&&<DashboardPage/>}{page==='Leads'&&<LeadsPage leads={leads} onMove={move}/>} {page==='Clientes'&&<ClientsPage/>}{page==='Atividades'&&<ActivitiesPage/>}</div></section><NewLeadDialog open={modal} onOpenChange={setModal} onCreate={create} initialDraft={prefill}/></main>}

function Logo(){return <div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-[#c7f14a] text-[#102c2b]"><Sparkles size={18}/></div><span className="text-[18px] font-semibold tracking-tight">FlowDesk</span></div>}
function NavItems({page,onNavigate}:{page:Page;onNavigate:(p:Page)=>void}){return <nav className="mt-10 space-y-1">{nav.map(({name,icon:Icon})=><button key={name} onClick={()=>onNavigate(name)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition ${page===name?'bg-white/10 font-medium text-white':'text-white/60 hover:bg-white/5 hover:text-white'}`}><Icon size={18} className={page===name?'text-[#c7f14a]':''}/>{name}{name==='Leads'&&<span className="ml-auto rounded-md bg-white/10 px-1.5 py-0.5 text-[10px]">15</span>}</button>)}</nav>}
function UserCard(){return <div className="mt-auto"><button className="mb-2 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-white/60 hover:bg-white/5 hover:text-white"><Settings size={18}/>Configurações</button><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-3"><p className="text-xs text-white/45">Equipe comercial</p><div className="mt-3 flex items-center gap-3"><div className="grid size-9 place-items-center rounded-full bg-[#d8a3ff] text-sm font-semibold text-[#362047]">JM</div><div><p className="text-sm font-medium text-white">João Martins</p><p className="text-xs text-white/45">Administrador</p></div></div></div></div>}
function DesktopSidebar({page,onNavigate}:{page:Page;onNavigate:(p:Page)=>void}){return <aside className="sticky top-0 hidden h-screen border-r border-white/10 bg-[#102c2b] px-4 py-5 text-white lg:flex lg:flex-col"><div className="px-2"><Logo/></div><NavItems page={page} onNavigate={onNavigate}/><UserCard/></aside>}
function MobileNav({page,onNavigate}:{page:Page;onNavigate:(p:Page)=>void}){const[open,setOpen]=useState(false);return <Sheet open={open} onOpenChange={setOpen}><SheetTrigger render={<Button variant="outline" size="icon" className="rounded-xl lg:hidden"/>}><Menu size={18}/></SheetTrigger><SheetContent side="left" className="flex w-[286px] flex-col border-none bg-[#102c2b] p-5 text-white"><SheetTitle className="sr-only">Menu principal</SheetTitle><Logo/><NavItems page={page} onNavigate={p=>{onNavigate(p);setOpen(false)}}/><UserCard/></SheetContent></Sheet>}
function AppHeader({page,onNavigate,onNew}:{page:Page;onNavigate:(p:Page)=>void;onNew:()=>void}){return <header className="sticky top-0 z-30 flex h-[76px] items-center justify-between border-b border-[#dde4e2] bg-white/90 px-4 backdrop-blur lg:px-8"><div className="flex items-center gap-3"><MobileNav page={page} onNavigate={onNavigate}/><div><p className="hidden text-xs font-medium uppercase tracking-[.14em] text-[#758481] sm:block">{page==='Dashboard'?'Visão geral':'Comercial'}</p><h1 className="text-lg font-semibold tracking-tight sm:text-xl">{page}</h1></div></div><div className="flex items-center gap-2"><label className="hidden items-center gap-2 rounded-xl border border-[#dfe6e4] bg-[#f8faf9] px-3 py-2 text-sm text-[#778582] md:flex"><Search size={16}/><input className="w-36 bg-transparent outline-none xl:w-48" placeholder="Buscar no FlowDesk"/><kbd className="rounded border bg-white px-1.5 py-0.5 text-[10px] text-[#8a9693]">⌘ K</kbd></label><Tooltip><TooltipTrigger render={<Button variant="outline" size="icon" className="relative rounded-xl" aria-label="Notificações"/>}><Bell size={17}/><span className="absolute right-2 top-2 size-1.5 rounded-full bg-[#df7e5c] ring-2 ring-white"/></TooltipTrigger><TooltipContent>3 notificações</TooltipContent></Tooltip><Button onClick={onNew} className="rounded-xl bg-[#173f3d] px-3 text-white hover:bg-[#0f302f] sm:px-4"><Plus size={17}/><span className="hidden sm:inline">Novo lead</span></Button></div></header>}

