'use client';

import { useMemo, useState } from 'react';
import { CalendarClock, Check, Clock3, Mail, Phone, Plus, RotateCcw, Trash2, UsersRound, Video } from 'lucide-react';
import type { Activity, ActivityStatus, ActivityType, Lead } from '@/types/crm';
import { SectionTitle } from '@/components/shared';
import { Button } from '@/components/ui/button';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';

type Period='all'|'today'|'overdue'|'upcoming'|'completed';
const typeIcons:Record<ActivityType,React.ReactNode>={Ligação:<Phone size={16}/>,Reunião:<Video size={16}/>,Email:<Mail size={16}/>,Tarefa:<Check size={16}/>};
const dayBounds=(now:number)=>{const start=new Date(now);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);return{start:start.getTime(),end:end.getTime()}};

export function ActivitiesPage({activities,leads,loading,onNew,onEdit,onToggle,onDelete,onOpenLead}:{activities:Activity[];leads:Lead[];loading:boolean;onNew:()=>void;onEdit:(activity:Activity)=>void;onToggle:(activity:Activity)=>Promise<void>;onDelete:(id:string)=>Promise<void>;onOpenLead:(id:string)=>void}){
  const [status,setStatus]=useState<'all'|ActivityStatus>('all');const [type,setType]=useState<'all'|ActivityType>('all');const [leadId,setLeadId]=useState('all');const [period,setPeriod]=useState<Period>('all');const [now]=useState(()=>Date.now());const {start,end}=dayBounds(now);
  const counts=useMemo(()=>({today:activities.filter(a=>a.status==='pending'&&new Date(a.scheduledAt).getTime()>=start&&new Date(a.scheduledAt).getTime()<end).length,overdue:activities.filter(a=>a.status==='pending'&&new Date(a.scheduledAt).getTime()<now).length,upcoming:activities.filter(a=>a.status==='pending'&&new Date(a.scheduledAt).getTime()>=end).length,completed:activities.filter(a=>a.status==='completed').length}),[activities,start,end,now]);
  const visible=useMemo(()=>activities.filter(a=>{const time=new Date(a.scheduledAt).getTime();if(status!=='all'&&a.status!==status)return false;if(type!=='all'&&a.type!==type)return false;if(leadId!=='all'&&a.leadId!==leadId)return false;if(period==='today'&&!(a.status==='pending'&&time>=start&&time<end))return false;if(period==='overdue'&&!(a.status==='pending'&&time<now))return false;if(period==='upcoming'&&!(a.status==='pending'&&time>=end))return false;if(period==='completed'&&a.status!=='completed')return false;return true;}),[activities,status,type,leadId,period,start,end,now]);
  if(loading)return <div className="card-surface p-12 text-center text-sm text-[var(--text-soft)]">Carregando atividades...</div>;
  return <><SectionTitle title="Atividades" description="Organize contatos, reuniões e tarefas comerciais em uma única agenda." action={<Button onClick={onNew} disabled={!leads.length} className="bg-[var(--brand-deep)] text-white dark:text-[#13231f]"><Plus size={16}/>Nova atividade</Button>}/><div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary label="Hoje" value={counts.today} icon={<CalendarClock size={17}/>} active={period==='today'} onClick={()=>setPeriod(period==='today'?'all':'today')}/><Summary label="Atrasadas" value={counts.overdue} icon={<Clock3 size={17}/>} active={period==='overdue'} onClick={()=>setPeriod(period==='overdue'?'all':'overdue')}/><Summary label="Próximas" value={counts.upcoming} icon={<UsersRound size={17}/>} active={period==='upcoming'} onClick={()=>setPeriod(period==='upcoming'?'all':'upcoming')}/><Summary label="Concluídas" value={counts.completed} icon={<Check size={17}/>} active={period==='completed'} onClick={()=>setPeriod(period==='completed'?'all':'completed')}/></div>{activities.length>0&&<div className="mb-4 grid gap-3 border border-[var(--line)] bg-[var(--surface-raised)] p-3 sm:grid-cols-3"><Filter label="Status" value={status} onChange={(value)=>setStatus(value as 'all'|ActivityStatus)}><option value="all">Todos</option><option value="pending">Pendentes</option><option value="completed">Concluídas</option></Filter><Filter label="Tipo" value={type} onChange={(value)=>setType(value as 'all'|ActivityType)}><option value="all">Todos</option><option>Ligação</option><option>Reunião</option><option>Email</option><option>Tarefa</option></Filter><Filter label="Lead" value={leadId} onChange={setLeadId}><option value="all">Todos os leads</option>{leads.map(lead=><option key={lead.id} value={lead.id}>{lead.name}</option>)}</Filter></div>}{activities.length===0?<section className="card-surface p-10 text-center sm:p-14"><CalendarClock className="mx-auto text-[var(--success)]" size={30}/><p className="mt-4 text-lg font-semibold text-[var(--text-strong)]">Sua agenda comercial está vazia</p><p className="mx-auto mt-2 max-w-md text-sm leading-relaxed text-[var(--text-soft)]">Crie a primeira atividade para acompanhar o próximo contato de um lead.</p><Button onClick={onNew} disabled={!leads.length} className="mt-5 bg-[var(--brand-deep)] text-white dark:text-[#13231f]"><Plus size={16}/>{leads.length?'Criar primeira atividade':'Cadastre um lead primeiro'}</Button></section>:visible.length===0?<section className="card-surface p-10 text-center text-sm text-[var(--text-soft)]">Nenhuma atividade corresponde aos filtros selecionados.</section>:<section className="card-surface divide-y divide-[var(--line-soft)] overflow-hidden">{visible.map(activity=><ActivityRow key={activity.id} activity={activity} now={now} onEdit={()=>onEdit(activity)} onToggle={()=>onToggle(activity)} onDelete={()=>onDelete(activity.id)} onOpenLead={()=>onOpenLead(activity.leadId)}/>)}</section>}</>;
}
function Summary({label,value,icon,active,onClick}:{label:string;value:number;icon:React.ReactNode;active:boolean;onClick:()=>void}){return <button onClick={onClick} className={`flex items-center gap-4 border p-4 text-left transition ${active?'border-[var(--success)] bg-[var(--brand-lime-soft)]':'border-[var(--line)] bg-[var(--surface-raised)] hover:border-[var(--success)]/50'}`}><span className="text-[var(--success)]">{icon}</span><span><span className="block text-xs text-[var(--text-faint)]">{label}</span><strong className="mt-0.5 block text-2xl text-[var(--text-strong)]">{value}</strong></span></button>}
function Filter({label,value,onChange,children}:{label:string;value:string;onChange:(value:string)=>void;children:React.ReactNode}){return <label><span className="sr-only">{label}</span><select aria-label={label} value={value} onChange={(e)=>onChange(e.target.value)} className="premium-input h-9 w-full rounded-md border px-3 text-sm">{children}</select></label>}
function ActivityRow({activity,now,onEdit,onToggle,onDelete,onOpenLead}:{activity:Activity;now:number;onEdit:()=>void;onToggle:()=>void;onDelete:()=>void;onOpenLead:()=>void}){const overdue=activity.status==='pending'&&new Date(activity.scheduledAt).getTime()<now;return <article className="grid gap-4 p-4 sm:p-5 lg:grid-cols-[auto_1fr_auto] lg:items-center"><span className={`grid size-10 place-items-center rounded-lg ${activity.status==='completed'?'bg-[var(--surface-soft)] text-[var(--text-faint)]':overdue?'bg-red-50 text-red-600 dark:bg-red-950/30 dark:text-red-300':'bg-[var(--brand-lime-soft)] text-[var(--success)]'}`}>{typeIcons[activity.type]}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className={`font-semibold ${activity.status==='completed'?'text-[var(--text-faint)] line-through':'text-[var(--text-strong)]'}`}>{activity.title}</h3><span className={`rounded-full px-2 py-0.5 text-xs ${overdue?'bg-red-50 text-red-700 dark:bg-red-950/30 dark:text-red-200':'bg-[var(--surface-soft)] text-[var(--text-soft)]'}`}>{activity.status==='completed'?'Concluída':overdue?'Atrasada':activity.type}</span></div><button onClick={onOpenLead} className="mt-1 text-sm font-medium text-[var(--success)] hover:underline">{activity.leadName} · {activity.leadCompany}</button><p className="mt-1 text-sm text-[var(--text-soft)]">{new Date(activity.scheduledAt).toLocaleString('pt-BR',{dateStyle:'medium',timeStyle:'short'})}{activity.description?` · ${activity.description}`:''}</p></div><div className="flex flex-wrap gap-2 lg:justify-end"><Button variant="outline" size="sm" onClick={onToggle}>{activity.status==='completed'?<><RotateCcw size={14}/>Reabrir</>:<><Check size={14}/>Concluir</>}</Button><Button variant="outline" size="sm" onClick={onEdit}>Editar</Button><AlertDialog><AlertDialogTrigger render={<Button variant="outline" size="icon-sm" aria-label={`Excluir ${activity.title}`}/>}><Trash2 size={14}/></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir esta atividade?</AlertDialogTitle><AlertDialogDescription>Esta ação removerá a atividade da agenda e atualizará a próxima ação do lead.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={onDelete} className="bg-red-600 text-white hover:bg-red-700">Excluir</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></article>}
