'use client';

import { useEffect, useState } from 'react';
import type { Activity, ActivityStatus, ActivityType, Lead } from '@/types/crm';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';

export type ActivityDraft={leadId:string;type:ActivityType;title:string;description:string;scheduledAt:string;status:ActivityStatus};
const types:ActivityType[]=['Ligação','Reunião','Email','Tarefa'];
const blank:ActivityDraft={leadId:'',type:'Ligação',title:'',description:'',scheduledAt:'',status:'pending'};
const localDate=(value:string)=>{const date=new Date(value);const offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16)};

export function ActivityDialog({open,onOpenChange,leads,activity,initialLeadId,onSave}:{open:boolean;onOpenChange:(open:boolean)=>void;leads:Lead[];activity:Activity|null;initialLeadId?:string|null;onSave:(draft:ActivityDraft,id?:string)=>Promise<void>}){
  const [form,setForm]=useState<ActivityDraft>(blank);const [pending,setPending]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{if(!open)return;const next=activity?{leadId:activity.leadId,type:activity.type,title:activity.title,description:activity.description,scheduledAt:localDate(activity.scheduledAt),status:activity.status}:{...blank,leadId:initialLeadId||leads[0]?.id||'',scheduledAt:localDate(new Date(Date.now()+3600000).toISOString())};queueMicrotask(()=>{setForm(next);setError('');});},[open,activity,initialLeadId,leads]);
  const set=<K extends keyof ActivityDraft>(key:K,value:ActivityDraft[K])=>setForm((current)=>({...current,[key]:value}));
  const submit=async(event:React.SyntheticEvent<HTMLFormElement>)=>{event.preventDefault();if(!form.leadId)return setError('Selecione um lead.');if(!form.title.trim())return setError('Informe o título da atividade.');if(!form.scheduledAt)return setError('Informe a data e o horário.');setPending(true);setError('');try{await onSave({...form,title:form.title.trim(),description:form.description.trim(),scheduledAt:new Date(form.scheduledAt).toISOString()},activity?.id);onOpenChange(false);}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível salvar a atividade.');}finally{setPending(false);}};
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-lg border border-[var(--line)] bg-[var(--surface-raised)] p-6"><DialogHeader><DialogTitle className="text-xl text-[var(--text-strong)]">{activity?'Editar atividade':'Nova atividade'}</DialogTitle><DialogDescription className="text-[var(--text-soft)]">Organize o próximo contato e mantenha o acompanhamento do lead em dia.</DialogDescription></DialogHeader><form noValidate onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Tipo"><select value={form.type} onChange={(e)=>set('type',e.target.value as ActivityType)} className="premium-input h-10 w-full rounded-md border px-3 text-sm">{types.map((type)=><option key={type}>{type}</option>)}</select></Field><Field label="Status"><select value={form.status} onChange={(e)=>set('status',e.target.value as ActivityStatus)} className="premium-input h-10 w-full rounded-md border px-3 text-sm"><option value="pending">Pendente</option><option value="completed">Concluída</option></select></Field></div><Field label="Lead relacionado *"><select value={form.leadId} onChange={(e)=>set('leadId',e.target.value)} className="premium-input h-10 w-full rounded-md border px-3 text-sm"><option value="">Selecione um lead</option>{leads.map((lead)=><option key={lead.id} value={lead.id}>{lead.name} — {lead.company}</option>)}</select></Field><Field label="Título *"><Input value={form.title} onChange={(e)=>set('title',e.target.value)} placeholder="Ex.: Apresentar proposta comercial" className="premium-input"/></Field><Field label="Data e horário *"><Input type="datetime-local" value={form.scheduledAt} onChange={(e)=>set('scheduledAt',e.target.value)} className="premium-input"/></Field><Field label="Observações"><Textarea value={form.description} onChange={(e)=>set('description',e.target.value)} placeholder="Contexto e pontos que devem ser tratados" className="premium-input min-h-24"/></Field>{error&&<p role="alert" className="border border-red-300/50 bg-red-50 px-3 py-2 text-sm text-red-700 dark:bg-red-950/30 dark:text-red-200">{error}</p>}<DialogFooter className="mt-6"><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button type="submit" disabled={pending||leads.length===0} className="bg-[var(--brand-deep)] text-white dark:text-[#13231f]">{pending?'Salvando...':activity?'Salvar alterações':'Criar atividade'}</Button></DialogFooter></form></DialogContent></Dialog>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block space-y-2"><span className="block text-sm font-medium text-[var(--text-soft)]">{label}</span>{children}</label>}
