'use client';
import { CalendarCheck, CheckCircle2, Mail, MessageCircle, Phone, RefreshCcw, SlidersHorizontal } from 'lucide-react';
import { useState } from 'react';
import { activities } from '@/data/activities';
import type { ActivityType } from '@/types/crm';
import { PersonAvatar, SectionTitle } from '@/components/shared';
import { Button } from '@/components/ui/button';

const icons = { Ligação: Phone, Reunião: CalendarCheck, Email: Mail, WhatsApp: MessageCircle, Atualização: RefreshCcw, Fechamento: CheckCircle2 };
const filters: ('Todas'|ActivityType)[]=['Todas','Ligação','Reunião','Email','WhatsApp','Atualização','Fechamento'];

export function ActivitiesPage(){ const [filter,setFilter]=useState<(typeof filters)[number]>('Todas'); const list=filter==='Todas'?activities:activities.filter(a=>a.type===filter); return <><SectionTitle title="Atividades" description="Histórico de interações e movimentações comerciais." action={<Button variant="outline" className="control-button"><SlidersHorizontal size={16}/> Mais filtros</Button>}/><div className="mb-4 flex gap-2 overflow-x-auto pb-1">{filters.map(f=><button onClick={()=>setFilter(f)} key={f} className={`whitespace-nowrap rounded-[9px] border px-3 py-2 text-[12px] font-medium transition ${filter===f?'border-[var(--brand-deep)] bg-[var(--brand-deep)] text-white shadow-sm dark:text-[#13231f]':'border-[var(--line)] bg-[var(--surface-raised)] text-[var(--text-soft)] hover:bg-[var(--surface-soft)] hover:text-[var(--text-strong)]'}`}>{f}</button>)}</div><section className="card-surface overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--line-soft)] px-5 py-4 sm:px-6"><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[var(--text-faint)]">Linha do tempo</p><p className="mt-1 text-sm font-medium text-[var(--text-strong)]">{list.length} registros encontrados</p></div><span className="flex items-center gap-2 text-[11px] text-[var(--text-faint)]"><span className="size-1.5 rounded-full bg-[var(--brand-lime)]"/>Atualizado agora</span></div><div className="relative space-y-1 p-3 sm:p-5 before:absolute before:bottom-10 before:left-[38px] before:top-10 before:w-px before:bg-[var(--line)] sm:before:left-[46px]">{list.map(a=>{const Icon=icons[a.type];return <article key={a.id} className="relative flex gap-4 rounded-[12px] p-3 transition hover:bg-[var(--surface-soft)]"><span className="z-10 grid size-10 shrink-0 place-items-center rounded-[10px] border border-[var(--line)] bg-[var(--surface-raised)] text-[var(--success)] shadow-sm"><Icon size={16}/></span><div className="min-w-0 flex-1 border-b border-[var(--line-soft)] pb-5"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><h3 className="text-[13px] font-semibold text-[var(--text-strong)]">{a.title}</h3><span className="rounded-[5px] border border-[var(--line-soft)] bg-[var(--surface-soft)] px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-[.05em] text-[var(--text-soft)]">{a.type}</span></div><time className="text-[11px] text-[var(--text-faint)]">{a.time}</time></div><p className="mt-1.5 text-[13px] text-[var(--text-soft)]">{a.description}</p><div className="mt-3 flex flex-wrap items-center gap-2"><PersonAvatar user={a.owner} small/><span className="text-[11px] font-medium text-[var(--text-strong)]">{a.lead}</span><span className="text-[11px] text-[var(--text-faint)]">· {a.owner.name}</span></div></div></article>})}</div></section></>; }
