'use client';
import { ChevronLeft, ChevronRight, Ellipsis, Plus, Search, SlidersHorizontal } from 'lucide-react';
import { clients } from '@/data/clients';
import { money, PersonAvatar, SectionTitle } from '@/components/shared';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { useState } from 'react';

export function ClientsPage() {
  const [query,setQuery]=useState('');
  const filtered=clients.filter(c=>`${c.name} ${c.company} ${c.email}`.toLowerCase().includes(query.toLowerCase()));
  return <><SectionTitle title="Clientes" description="Acompanhe sua carteira e mantenha relacionamentos em dia." action={<Button className="h-9 rounded-[10px] bg-[var(--brand-deep)] text-white hover:opacity-90 dark:text-[#13231f]"><Plus size={16}/> Adicionar cliente</Button>}/>
    <section className="card-surface overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--line-soft)] p-4 sm:px-5"><div className="relative"><Search className="absolute left-3 top-2.5 text-[var(--text-faint)]" size={15}/><Input value={query} onChange={e=>setQuery(e.target.value)} className="premium-input w-[min(72vw,320px)] rounded-[10px] pl-9 text-[13px]" placeholder="Pesquisar clientes..."/></div><div className="flex items-center gap-2"><span className="hidden text-[11px] text-[var(--text-faint)] sm:inline">8 registros</span><Button variant="outline" className="control-button"><SlidersHorizontal size={15}/> Todos os status</Button></div></div>
      <div className="overflow-x-auto"><Table><TableHeader><TableRow className="border-[var(--line-soft)] bg-[var(--surface-soft)] hover:bg-[var(--surface-soft)]"><TableHead className="text-[10px] font-semibold uppercase tracking-[.09em] text-[var(--text-faint)]">Cliente</TableHead><TableHead>Empresa</TableHead><TableHead>Email</TableHead><TableHead>Telefone</TableHead><TableHead>Status</TableHead><TableHead>Valor total</TableHead><TableHead>Último contato</TableHead><TableHead>Responsável</TableHead><TableHead/></TableRow></TableHeader><TableBody>{filtered.map(c=><TableRow key={c.id} className="h-[68px] border-[var(--line-soft)] hover:bg-[var(--surface-soft)]/70"><TableCell className="font-semibold text-[var(--text-strong)]">{c.name}</TableCell><TableCell className="text-[var(--text-soft)]">{c.company}</TableCell><TableCell className="text-[var(--text-soft)]">{c.email}</TableCell><TableCell className="whitespace-nowrap text-[var(--text-soft)]">{c.phone}</TableCell><TableCell><Badge variant="outline" className={c.status==='Ativo'?'border-[#75a996]/30 bg-[#75a996]/10 text-[var(--success)]':c.status==='Em risco'?'border-[#d5a14c]/30 bg-[#d5a14c]/10 text-[#b47a21] dark:text-[#e1ae5c]':'border-[var(--line)] bg-[var(--surface-soft)] text-[var(--text-soft)]'}>{c.status}</Badge></TableCell><TableCell className="font-semibold text-[var(--text-strong)]">{money(c.totalValue)}</TableCell><TableCell className="whitespace-nowrap text-[var(--text-soft)]">{c.lastContact}</TableCell><TableCell><div className="flex items-center gap-2"><PersonAvatar user={c.owner} small/><span className="whitespace-nowrap text-sm text-[var(--text-strong)]">{c.owner.name.split(' ')[0]}</span></div></TableCell><TableCell><DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon" className="text-[var(--text-faint)]" aria-label={`Ações para ${c.name}`}/>}><Ellipsis size={17}/></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem>Ver detalhes</DropdownMenuItem><DropdownMenuItem>Editar cliente</DropdownMenuItem><DropdownMenuItem>Registrar atividade</DropdownMenuItem></DropdownMenuContent></DropdownMenu></TableCell></TableRow>)}</TableBody></Table></div>
      {filtered.length===0&&<div className="p-12 text-center"><p className="font-medium text-[var(--text-strong)]">Nenhum cliente encontrado</p><p className="mt-1 text-sm text-[var(--text-soft)]">Tente pesquisar por outro nome ou empresa.</p></div>}
      <footer className="flex items-center justify-between border-t border-[var(--line-soft)] px-4 py-3 text-xs text-[var(--text-soft)] sm:px-5"><span>Exibindo {filtered.length} de {clients.length} clientes</span><div className="flex items-center gap-1"><Button variant="outline" size="icon-sm" className="control-button" disabled><ChevronLeft size={15}/></Button><Button size="sm" className="bg-[var(--brand-deep)] text-white dark:text-[#13231f]">1</Button><Button variant="outline" size="sm" className="control-button">2</Button><Button variant="outline" size="icon-sm" className="control-button"><ChevronRight size={15}/></Button></div></footer></section></>;
}
